spring:
  application:
    name: dubbo-consumer-demo
  cloud:
    sentinel:
      transport:
        dashboard: ubuntu:8080
        port: 8719
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://ubuntu:8848
  protocol:
    name: dubbo

server:
  port: 8080